- README.md
- helm/csi-charts/templates/daemonset.yaml
This PR removes deployment of iscsi and multipath sidecars and updates README with the steps required to install iscsid and multipath-tools on every node
-----
[View rendered README.md](https://github.com/gregnsk/seagate-exos-x-csi/blob/disable-iscsi-sidecar/README.md)
> Disable iscsi sidecar

- Makefile
- helm/csi-charts/Chart.yaml
- helm/csi-charts/values.yaml
- pkg/node/node.go
- Version 0.5.5
- Changed blkid to use single dash switches which are supported in older and new versions
- Corrected the Makefile to work with env variables.
> v0.5.5 updates to use older blkid options for compatibility reasons

- pkg/common/driver.go
- pkg/common/system.go
- pkg/controller/controller.go
- pkg/controller/snapshotter.go
- pkg/node/node.go
- test/sanity-cli
- test/secrets.template.yml
- Correction to GetParamerers to allocate a map object, not a pointer to a map object
- Correction made to properly handle TranslateName(), which takes a CO volume/snapshot name and modifies it to work with exos-x storage
- Updated the csi-sanity template to include ListSnapshotSecrets
- Updated sanity-cli to all a parameter of "all" which will ignore -ginko.focus and run all tests
- Corrections to NodeUnpublishVolume to conform to CSI rpc specification
- Corrections to NodeExpandVolume to conform to CSI rpc specification
- Corrections to ListSnapshots to conform to CSI rpc specification
> fix: code adjustments to pass csi-sanity ListSnapshots tests

- pkg/controller/provisioner.go
- pkg/controller/snapshotter.go
Use VolumeIdGetName to retrieve the 'unaugmented' volume id to fix 'unmatched quotes' errors in certain api calls
> bug: fix mismatched quote errors from passing augmented volumeid

- helm/csi-charts/templates/daemonset.yaml
- helm/csi-charts/templates/deployment.yaml
imagePullSecrets may be needed if pulling the driver container images
from a registry that requires authentication. This can be useful for
development or if the external registries are not directly accessible
> test: add option to specify imagePullSecrets

- helm/csi-charts/templates/deployment.yaml
Error when starting up the controller deployment as this directory doesn't exist in the helm charts yet. 
Add the volume mount for the "run dir" to the deployment for the controller, used for storage of initiator map information
> fix: Add volume mount for controller run dir

- Makefile
- cmd/controller/controller.go
- cmd/node/node.go
- go.mod
- go.sum
- helm/csi-charts/values.yaml
- pkg/common/driver.go
- pkg/common/stringlock.go
- pkg/common/system.go
- pkg/controller/controller.go
- pkg/controller/expander.go
- pkg/controller/provisioner.go
- pkg/controller/publisher.go
- pkg/controller/snapshotter.go
- pkg/exporter/exporter.go
- pkg/node/node.go
- pkg/storage/fcNode.go
- pkg/storage/iscsiNode.go
- pkg/storage/sasNode.go
- pkg/storage/storageService.go
To mitigate possibility of a device that is in the process of being removed from being re-discovered by a subsequent NodePublishVolume call, maintain a list of previously removed devices and search for / re-remove them during publishing
> Hs 312/sas device not found

- go.mod
- go.sum
- helm/csi-charts/values.yaml
- pkg/common/driver.go
- pkg/common/system.go
- pkg/controller/provisioner.go
- pkg/controller/publisher.go
- pkg/node/node.go
Pass the node ID with the topology map so ControllerPublishVolume can tell which initiators are present on the scheduled node
> fix: Pass node ID with the topology map for initiator selection

- docs/sas/README.md
- helm/csi-charts/values.yaml
- pkg/controller/provisioner.go
- pkg/node/node.go
- pkg/storage/fcNode.go
- pkg/storage/iscsiNode.go
- pkg/storage/sasNode.go
- pkg/storage/storageService.go
Fixes a bug with XFS when checking for filesystem corruption. Removes corruption checks at Unpublish. Also adds topology parsing code to return accessibleTopology from Create Volume, which may be used by a CO scheduler in the future to determine pod scheduling requirements based on storage accessibility
> fix: Fix XFS compatibility and return accessible topology

- pkg/common/driver.go
Use a 31 character destination volume name to work around a controller issue that causes 32 character names to get truncated
resolves #61
> fix(snapshots): Use 31 char volume names for copy volume

- pkg/storage/storageService.go
In order to meet idempotency requirements, don't run (and fail) FS checks on an already mounted filesystem in NodePublishVolume
> fix: Do not run filesystem checks if fs is already mounted

- helm/csi-charts/values.yaml
k8s.gcr.io is deprecated and will be shutdown. Replace with the new registry.k8s.io.
> chore: Update default registry address to use registry.k8s.io

- pkg/storage/fcNode.go
device rediscovery prevention code was added for the SAS nodes. Port this code into the FC node as well.
> fix: Port device rediscovery check into FC node

- .github/workflows/publish.yml
move our default release image from the UBI based container to the openshift compliant containers (Dockerfile.redhat)
> fix: Update workflow to use Openshift compliant Dockerfile

- .github/workflows/publish.yml
Updates various actions to the latest versions to remove deprecated set-state and set-output commands and node.js versions. Replaces the fetch latest release action with a new curl/jq command as there was no updated version without the deprecated set-output command.
> build: Update deprecated actions in publish.yml

- .github/workflows/release.yml
The node version used in action checkout v2 is deprecated. Update to checkout v3
> build: Update github release action to use actions v3

- .github/workflows/publish.yml
Install protocol buffer compiler into github runner to support node gRPC service build step
> build: Install protocol buffer compiler for gRPC service build

- .github/workflows/publish.yml
Adds additional dependencies (protoc-gen-go-grpc, protoc-gen-go) and path updates needed for the gRPC service build step.
> build: install protoc and gRPC tools for building node service

- pkg/node_service/node_service_server.go
Previously the driver defaulted to iSCSI if no protocol was specified, a holdover from being iSCSI only initially. This change restores that behavior for the new gRPC initiator retrieval service.
> fix: default to iSCSI if no initiator type specified

- Makefile
- README.md
- helm/csi-charts/Chart.yaml
- helm/csi-charts/values.yaml
Added (more) support for automating the process of resubmitting the driver for Red Hat certification.
The Helm values.yaml file was run through yq to remove blank space, so future automated updates to the version number will not show so many changes to the file.
The README was updated to describe the method for installing the driver with a single command using a link to the helm package on the Github repo.
> certification automation, Helm chart formatting, README updates

- pkg/controller/publisher.go
Resolves recent sanity failures by returning the correct error code (5, Not Found) when the provided node ID in controllerpublishvolume is not valid/reachable.
> HS-306/invalid node return code

- cmd/controller/controller.go
- cmd/node/node.go
- pkg/common/driver.go
- pkg/controller/controller.go
- pkg/controller/publisher.go
- pkg/node/node.go
- pkg/node_service/node_service_client.go
- pkg/node_service/node_service_server.go
- pkg/storage/fcNode.go
- pkg/storage/sasNode.go
- pkg/storage/storageService.go
Utilizing the node-controller RPC communication server, notify node after a volume has completed controller unmap, so that it can stop checking for device rediscovery.
Also adds re-use of the grpc.ClientConn objects for better performance, as well as graceful shutdown of grpc clients and servers
> perf: Update node-controller rpc service to notify nodes on volume unmap

- Dockerfile.redhat
- Makefile
- helm/csi-charts/values.yaml
We don't need the go-toolset included in the final container image, use standard ubi7 as a base image instead. Additionally this release will trigger a build using the new version of the ubi7-go-toolset-1.19 container images which address several CVEs. See https://access.redhat.com/errata/RHSA-2023:3920 for details on the security fixes.
> fix: Use ubi7 instead of ubi7/go-toolset for final image

- Dockerfile.redhat
- Makefile
- go.mod
- go.sum
- helm/csi-charts/values.yaml
- pkg/controller/provisioner.go
Integrates exos API Lib update 2.2.0 to omit the tier-affinity parameter from Create Volume calls, resolving a compatibility issue with linear storage pools.
> chore: Update for api lib 2.2.0 create volume change

- Makefile
This PR removes the 'preflight-build' target, and changes the default preflight executable path to ../openshift-preflight/preflight-linux-amd64
On submission preflight now checks the release version against a list of currently supported versions. When building from source, preflight uses a version of 0.0.0 which will not be accepted, so we now use one downloaded from the Releases page of the preflight repository. 
Also update the 'docker run' command to 'start' an existing stopped local registry container if it exists. If it does not exist the previous 'docker run' command will execute.
> build: update preflight process
